### ISSUE TITLE
AZURE_SUBSCRIPTION_ID not set?

### ISSUE THREAD

**Issue by pl4nty** [feeloor/azure-static-website-deploy#3]
Deployment fails with `AZURE_SUBSCRIPTION_ID is not set. Quitting.` when set manually or with a secret:

```
Run feeloor/azure-static-website-deploy@v0.1.0
  with:
    SOURCE_DIR: ./dist
    AZURE_CLIENT_ID: ***
    AZURE_TENANT_ID: ***
    AZURE_SECRET: ***
    AZURE_SUBSCRIPTION_ID: 8e8bbf73-03c1-44da-a079-6db5df3c079d
    AZURE_STORAGE_ACCOUNT_NAME: ***
    AZURE_INDEX_DOCUMENT_NAME: taskpane.html
  env:
    NODE_VERSION: 12.13.0
/usr/bin/docker run --name d3c13181dd067a419cabb488171d34ab37_12f4ad --label 3888d3 --workdir /github/workspace --rm -e NODE_VERSION -e INPUT_SOURCE_DIR -e INPUT_AZURE_CLIENT_ID -e INPUT_AZURE_TENANT_ID -e INPUT_AZURE_SECRET -e INPUT_AZURE_SUBSCRIPTION_ID -e INPUT_AZURE_STORAGE_ACCOUNT_NAME -e INPUT_AZURE_INDEX_DOCUMENT_NAME -e INPUT_AZURE_ERROR_DOCUMENT_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/***/***":"/github/workspace" 3888d3:c13181dd067a419cabb488171d34ab37  "./dist" "***" "***" "***" "8e8bbf73-03c1-44da-a079-6db5df3c079d" "***" "taskpane.html" ""
AZURE_SUBSCRIPTION_ID is not set. Quitting.
```

My action config:

```
- name: Deploy
  uses: feeloor/azure-static-website-deploy@v0.1.0
  with:
    SOURCE_DIR: './dist'
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
    AZURE_SUBSCRIPTION_ID: '8e8bbf73-03c1-44da-a079-6db5df3c079d'
    AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
    AZURE_INDEX_DOCUMENT_NAME: 'taskpane.html'
```
